// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server/streamDescription.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	server/streamDescription.proto

It has these top-level messages:
	Tickers
	ExchangeTickers
	Ticker
	WhoAreYouParams
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Tickers struct {
	ExchangeTickers []*ExchangeTickers `protobuf:"bytes,1,rep,name=exchangeTickers" json:"exchangeTickers,omitempty"`
}

func (m *Tickers) Reset()                    { *m = Tickers{} }
func (m *Tickers) String() string            { return proto.CompactTextString(m) }
func (*Tickers) ProtoMessage()               {}
func (*Tickers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Tickers) GetExchangeTickers() []*ExchangeTickers {
	if m != nil {
		return m.ExchangeTickers
	}
	return nil
}

type ExchangeTickers struct {
	TimpeStamp int64     `protobuf:"varint,1,opt,name=timpeStamp" json:"timpeStamp,omitempty"`
	Exchange   string    `protobuf:"bytes,2,opt,name=exchange" json:"exchange,omitempty"`
	Tickers    []*Ticker `protobuf:"bytes,3,rep,name=tickers" json:"tickers,omitempty"`
}

func (m *ExchangeTickers) Reset()                    { *m = ExchangeTickers{} }
func (m *ExchangeTickers) String() string            { return proto.CompactTextString(m) }
func (*ExchangeTickers) ProtoMessage()               {}
func (*ExchangeTickers) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ExchangeTickers) GetTimpeStamp() int64 {
	if m != nil {
		return m.TimpeStamp
	}
	return 0
}

func (m *ExchangeTickers) GetExchange() string {
	if m != nil {
		return m.Exchange
	}
	return ""
}

func (m *ExchangeTickers) GetTickers() []*Ticker {
	if m != nil {
		return m.Tickers
	}
	return nil
}

type Ticker struct {
	Symbol               string `protobuf:"bytes,1,opt,name=symbol" json:"symbol,omitempty"`
	Rate                 string `protobuf:"bytes,2,opt,name=rate" json:"rate,omitempty"`
	TargetCurrencyId     int64  `protobuf:"varint,3,opt,name=targetCurrencyId" json:"targetCurrencyId,omitempty"`
	ReferrenceCurrencyId int64  `protobuf:"varint,4,opt,name=referrenceCurrencyId" json:"referrenceCurrencyId,omitempty"`
}

func (m *Ticker) Reset()                    { *m = Ticker{} }
func (m *Ticker) String() string            { return proto.CompactTextString(m) }
func (*Ticker) ProtoMessage()               {}
func (*Ticker) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Ticker) GetSymbol() string {
	if m != nil {
		return m.Symbol
	}
	return ""
}

func (m *Ticker) GetRate() string {
	if m != nil {
		return m.Rate
	}
	return ""
}

func (m *Ticker) GetTargetCurrencyId() int64 {
	if m != nil {
		return m.TargetCurrencyId
	}
	return 0
}

func (m *Ticker) GetReferrenceCurrencyId() int64 {
	if m != nil {
		return m.ReferrenceCurrencyId
	}
	return 0
}

type WhoAreYouParams struct {
}

func (m *WhoAreYouParams) Reset()                    { *m = WhoAreYouParams{} }
func (m *WhoAreYouParams) String() string            { return proto.CompactTextString(m) }
func (*WhoAreYouParams) ProtoMessage()               {}
func (*WhoAreYouParams) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func init() {
	proto.RegisterType((*Tickers)(nil), "server.Tickers")
	proto.RegisterType((*ExchangeTickers)(nil), "server.ExchangeTickers")
	proto.RegisterType((*Ticker)(nil), "server.Ticker")
	proto.RegisterType((*WhoAreYouParams)(nil), "server.WhoAreYouParams")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for TickerGRPCServer service

type TickerGRPCServerClient interface {
	Tickers(ctx context.Context, in *WhoAreYouParams, opts ...grpc.CallOption) (TickerGRPCServer_TickersClient, error)
}

type tickerGRPCServerClient struct {
	cc *grpc.ClientConn
}

func NewTickerGRPCServerClient(cc *grpc.ClientConn) TickerGRPCServerClient {
	return &tickerGRPCServerClient{cc}
}

func (c *tickerGRPCServerClient) Tickers(ctx context.Context, in *WhoAreYouParams, opts ...grpc.CallOption) (TickerGRPCServer_TickersClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_TickerGRPCServer_serviceDesc.Streams[0], c.cc, "/server.TickerGRPCServer/tickers", opts...)
	if err != nil {
		return nil, err
	}
	x := &tickerGRPCServerTickersClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type TickerGRPCServer_TickersClient interface {
	Recv() (*Tickers, error)
	grpc.ClientStream
}

type tickerGRPCServerTickersClient struct {
	grpc.ClientStream
}

func (x *tickerGRPCServerTickersClient) Recv() (*Tickers, error) {
	m := new(Tickers)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for TickerGRPCServer service

type TickerGRPCServerServer interface {
	Tickers(*WhoAreYouParams, TickerGRPCServer_TickersServer) error
}

func RegisterTickerGRPCServerServer(s *grpc.Server, srv TickerGRPCServerServer) {
	s.RegisterService(&_TickerGRPCServer_serviceDesc, srv)
}

func _TickerGRPCServer_Tickers_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(WhoAreYouParams)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(TickerGRPCServerServer).Tickers(m, &tickerGRPCServerTickersServer{stream})
}

type TickerGRPCServer_TickersServer interface {
	Send(*Tickers) error
	grpc.ServerStream
}

type tickerGRPCServerTickersServer struct {
	grpc.ServerStream
}

func (x *tickerGRPCServerTickersServer) Send(m *Tickers) error {
	return x.ServerStream.SendMsg(m)
}

var _TickerGRPCServer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "server.TickerGRPCServer",
	HandlerType: (*TickerGRPCServerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "tickers",
			Handler:       _TickerGRPCServer_Tickers_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "server/streamDescription.proto",
}

func init() { proto.RegisterFile("server/streamDescription.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 288 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x51, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x75, 0x4d, 0x49, 0xed, 0x08, 0xa6, 0x0e, 0xa2, 0xa1, 0x87, 0x52, 0x72, 0x0a, 0x1e, 0xaa,
	0xd4, 0x83, 0xe7, 0x52, 0x45, 0x44, 0x0f, 0x65, 0x2b, 0x88, 0xc7, 0x6d, 0x1c, 0xdb, 0xa0, 0xe9,
	0x86, 0xd9, 0xad, 0xda, 0xff, 0xe1, 0x0f, 0x16, 0x36, 0x1f, 0xb4, 0xd1, 0xdb, 0xbe, 0x8f, 0x9d,
	0x79, 0x6f, 0x17, 0xfa, 0x86, 0xf8, 0x93, 0xf8, 0xc2, 0x58, 0x26, 0x95, 0xdd, 0x90, 0x49, 0x38,
	0xcd, 0x6d, 0xaa, 0x57, 0xc3, 0x9c, 0xb5, 0xd5, 0xe8, 0x17, 0x7a, 0xf4, 0x08, 0xed, 0xa7, 0x34,
	0x79, 0x27, 0x36, 0x38, 0x86, 0x80, 0xbe, 0x93, 0xa5, 0x5a, 0x2d, 0xa8, 0xa4, 0x42, 0x31, 0xf0,
	0xe2, 0xc3, 0xd1, 0xd9, 0xb0, 0x30, 0x0f, 0x6f, 0x77, 0x65, 0xd9, 0xf4, 0x47, 0x5f, 0x10, 0x34,
	0x3c, 0xd8, 0x07, 0xb0, 0x69, 0x96, 0xd3, 0xcc, 0xaa, 0x2c, 0x0f, 0xc5, 0x40, 0xc4, 0x9e, 0xdc,
	0x62, 0xb0, 0x07, 0x07, 0xd5, 0x94, 0x70, 0x7f, 0x20, 0xe2, 0x8e, 0xac, 0x31, 0xc6, 0xd0, 0xb6,
	0x65, 0x12, 0xcf, 0x25, 0x39, 0xaa, 0x92, 0x14, 0xd3, 0x65, 0x25, 0x47, 0x3f, 0x02, 0xfc, 0x82,
	0xc3, 0x53, 0xf0, 0xcd, 0x26, 0x9b, 0xeb, 0x0f, 0xb7, 0xac, 0x23, 0x4b, 0x84, 0x08, 0x2d, 0x56,
	0xb6, 0x5a, 0xe2, 0xce, 0x78, 0x0e, 0x5d, 0xab, 0x78, 0x41, 0x76, 0xb2, 0x66, 0xa6, 0x55, 0xb2,
	0xb9, 0x7f, 0x0d, 0x3d, 0x17, 0xf1, 0x0f, 0x8f, 0x23, 0x38, 0x61, 0x7a, 0x23, 0x87, 0x69, 0xcb,
	0xdf, 0x72, 0xfe, 0x7f, 0xb5, 0xe8, 0x18, 0x82, 0xe7, 0xa5, 0x1e, 0x33, 0xbd, 0xe8, 0xf5, 0x54,
	0xb1, 0xca, 0xcc, 0xe8, 0x01, 0xba, 0x45, 0xd0, 0x3b, 0x39, 0x9d, 0xcc, 0x5c, 0x1b, 0xbc, 0xae,
	0x7b, 0x62, 0xfd, 0xd6, 0x8d, 0x7b, 0xbd, 0x60, 0xb7, 0xba, 0x89, 0xf6, 0x2e, 0xc5, 0xdc, 0x77,
	0x9f, 0x79, 0xf5, 0x1b, 0x00, 0x00, 0xff, 0xff, 0xf5, 0xe0, 0x95, 0xa2, 0xee, 0x01, 0x00, 0x00,
}
